In [1]:
conda install -c conda-forge imbalanced-learn  #install imbalance to import imblearn, which is used for undersampling

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [1]:
import scipy.io
import pandas as pd
import numpy as np
import os


from sklearn.metrics import  accuracy_score, confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from imblearn import under_sampling
from imblearn.under_sampling import NearMiss
from imblearn.over_sampling import RandomOverSampler

from scipy.io import loadmat

In [2]:
x = loadmat("/Users/malliksiddarth/Desktop/Data for Problem 3/X_train_digits.mat")
y = loadmat("/Users/malliksiddarth/Desktop/Data for Problem 3/Y_train_digits.mat")
x1 = loadmat("/Users/malliksiddarth/Desktop/Data for Problem 3/X_test_digits.mat")
y1 = loadmat("/Users/malliksiddarth/Desktop/Data for Problem 3/Y_test_digits.mat")

In [3]:
X_train = pd.DataFrame(x.get("X_train")) #creating dataframe for train dataset to convert .mat to pandas 
Y_train = pd.DataFrame(y.get("y_train"))

In [4]:
X_train.head #after creating pandas data frame, now data is in csv format not .mat

<bound method NDFrame.head of        0    1   2    3   4    5    6   7    8   9    10  11  12   13   14   15
0       0   80  44  100  47   91   47  58   48  24   16   0  27    1  100    3
1      32  100   0   80   6   56  100  56   57  88   47  84  55   38   60    0
2       0   75  45  100  45   95   44  61   45  27   15   0  34    1  100    5
3      49   74  14   40  28    0   78  14  100  56   71  93  18  100    0   64
4     100   93  38  100  21   67   85  34   62   0    0  20  50   57   88   93
...   ...  ...  ..  ...  ..  ...  ...  ..  ...  ..  ...  ..  ..  ...  ...  ...
6995    0   82  33  100  77   93   50  66   71  47  100  24  58    7   11    0
6996   12   96   3   66  76   40   64   0   16  17    0  60   7   98  100  100
6997  100   96  98  100  82   83   68  66   52  49   32  33  20   16    0    0
6998    0   82  24  100  54   99   50  61   34  27   41   0  71    6  100   17
6999   21  100  19   70  32  100   45  52   63   7    0   0  34    8  100   13

[7000 rows x 16 colum

In [5]:
X_test = pd.DataFrame(x1.get("X_test"))
Y_test = pd.DataFrame(y1.get("y_test")) #same above, for test

In [6]:
X_train,X_test,Y_train,Y_test=train_test_split(X_train,Y_train,train_size=0.5)

In [7]:
log_Class=LogisticRegression()
grid={ 'C':10.0**np.arange(-2,3),'penalty':['l1','l2']}   #model logisticRegression 
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [8]:
clf=GridSearchCV(log_Class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')  #crossvalidation 
clf.fit(X_train,Y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [9]:
Y_pred=clf.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[3102   19]
 [  16  363]]
0.99
              precision    recall  f1-score   support

           1       0.99      0.99      0.99      3121
           2       0.95      0.96      0.95       379

    accuracy                           0.99      3500
   macro avg       0.97      0.98      0.97      3500
weighted avg       0.99      0.99      0.99      3500



Undersampling 

In [10]:
NS=NearMiss(0.5)
X_trainns,Y_trainns=NS.fit_sample(X_train,Y_train)

/opt/anaconda3/lib/python3.8/site-packages/imblearn/utils/_validation.py:635: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


In [11]:
log_Class1=LogisticRegression()
grid={ 'C':10.0**np.arange(-2,3),'penalty':['l1','l2']}   #model logisticRegression 
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [12]:
clf1=GridSearchCV(log_Class1,grid,cv=cv,n_jobs=-1,scoring='f1_macro')  #crossvalidation 
clf1.fit(X_trainns,Y_trainns)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [13]:
Y_pred1=clf1.predict(X_test)
print(confusion_matrix(Y_test,Y_pred1))
print(accuracy_score(Y_test,Y_pred1))
print(classification_report(Y_test,Y_pred1))

[[3077   44]
 [  20  359]]
0.9817142857142858
              precision    recall  f1-score   support

           1       0.99      0.99      0.99      3121
           2       0.89      0.95      0.92       379

    accuracy                           0.98      3500
   macro avg       0.94      0.97      0.95      3500
weighted avg       0.98      0.98      0.98      3500



#OverSampling 

In [30]:
OS=RandomOverSampler(0.5)
X_trainns1,Y_trainns1=OS.fit_sample(X_train,Y_train)

/opt/anaconda3/lib/python3.8/site-packages/imblearn/utils/_validation.py:635: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


In [31]:
log_Class2=LogisticRegression()
grid={ 'C':10.0**np.arange(-2,3),'penalty':['l1','l2']}   #model logisticRegression 
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [32]:
clf2=GridSearchCV(log_Class2,grid,cv=cv,n_jobs=-1,scoring='f1_macro')  #crossvalidation 
clf2.fit(X_trainns1,Y_trainns1)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [33]:
Y_pred2=clf2.predict(X_test)
print(confusion_matrix(Y_test,Y_pred2))
print(accuracy_score(Y_test,Y_pred2))
print(classification_report(Y_test,Y_pred2))

[[3092   29]
 [   8  371]]
0.9894285714285714
              precision    recall  f1-score   support

           1       1.00      0.99      0.99      3121
           2       0.93      0.98      0.95       379

    accuracy                           0.99      3500
   macro avg       0.96      0.98      0.97      3500
weighted avg       0.99      0.99      0.99      3500

